### ISSUE TITLE
Inconsistent active links when using route path with optional route params

### ISSUE THREAD

**Issue by ruffle1986** [reactjs/react-router#3527] opened 2016-06-10 08:29 UTC
React Router Version: 2.4.1
React: 15.1.0

I have the following router configuration:
```js
<Router history={ browserHistory }>
  <Route path="/webshop(/:type)" component={ Webshop } />
</Router>
```

And here's my main app with links:
```js
const Webshop = () => (
  <div>
    <ul>
      <li>
        <Link to="/webshop" activeClassName="active">Webshop</Link>
        <ul>
          <li>
            <Link to="/webshop/bikes" activeClassName="active">
            Bikes
            </Link>
          </li>
        </ul>
      </li>
    </ul>
  </div>
);
```

Am I wrong when I'd like the link `Webshop` to be "active" when the user clicks on `Bikes`?

It could be really useful for nested category navigations when the parent category is active (therefore its children are visible) even when the user is on a child category page.

If I'm wrong, please, let me know. Any idea how I can solve this problem?

Here's a working jsbin:
http://jsbin.com/habepunena/edit?html,css,js,output

In the example above, when the user clicks on `Bikes` it won't be visible anymore because `Webshop` stops being active.

NOTE: I'm solving the parent-child visibility problem with the css's sibling selector because I didn't want to put a link into another.

**Comment by taion** [comment] 2016-06-10 14:30
Dupe of https://github.com/reactjs/react-router/issues/3277, https://github.com/reactjs/react-router/issues/3233, &c.

**Closed by taion** 2016-06-10 14:30 UTC
