### ISSUE TITLE
Depreciation Warning from History thrown in react-router 2.3.0

### ISSUE THREAD

**Issue by BerndWessels** [reactjs/react-router#3398] opened 2016-04-28 01:51 UTC
Hi
lately I get the following depreciation warning thrown:

    browser.js:49 Warning: Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href> are subtly different from basename. Please pass the basename explicitly in the options to createHistory

That is with `react-router` version `2.3.0`.

Are you guys aware of this, or am I doing something wrong?

**Comment by timdorr** [comment] 2016-04-28 02:55
Dupe of #3387 

Upgrade to `history` 2.1.1.

**Closed by timdorr** 2016-04-28 02:55 UTC
