### ISSUE TITLE
`npm view react-router` returns no data, `npm outdated` skips react-router

### ISSUE THREAD

**Issue by joeframbach** [reactjs/react-router#3170] opened 2016-03-11 00:04 UTC
## Version
2.0.0

## Test Case

```bash
npm view react-router
```

## Steps to reproduce

```bash
npm view react-router
```

## Expected Behavior

Should receive a gigantic unwieldy blob of json.

## Actual Behavior

Receive nothing.

## Steps to reproduce

```bash
npm outdated
```

## Expected Behavior

Should be told that my `0.3.1` installation is out of date.

## Actual Behavior

Receive nothing.

**Comment by taion** [comment] 2016-03-11 00:07
Confirmed. Wonder if it's something to do with unpublishing that errant 2.0.9-rc release or whatever it was. This is probably an npm bug, though.

**Comment by taion** [comment] 2016-03-11 00:10
@ryanflorence Did something go wrong with the 2.0.1 release? Looks like it's not tagged under `npm dist-tag ls react-router`.

**Comment by iarna** [comment] 2016-03-11 00:27
As @othiym23 says over in https://github.com/npm/npm/issues/11852, `latest` is set to `0.3.2` which doesn't exist. This can be corrected with `npm dist-tag add react-router@VERSION latest`.

**Comment by iarna** [comment] 2016-03-11 00:27
(Where `VERSION` is whatever version you want folks to get by default)

**Comment by taion** [comment] 2016-03-11 00:29
@iarna @othiym23 Thanks! I think @ryanflorence tried to tag a release on async-props but accidentally ran `npm dist-tag` from the wrong repo. I even checked the tags but didn't look at the output closely enough.

**Comment by taion** [comment] 2016-03-11 01:59
Looks like this has been fixed now. @ryanflorence Can you drop the `next: 2.0.0` dist-tag when you get a chance?

**Closed** 2016-03-11 01:59 UTC
