### ISSUE TITLE
Make <Link> rerender by itself instead of relying on parent to rerender it.

### ISSUE THREAD

**Issue by geekyme** [reactjs/react-router#3200] opened 2016-03-18 11:25 UTC
## Version
2.0.1

## Scenario

Assume I have a `<List>` component holding a list of `<Child>`. Each child receive props from the parent and implements `shouldComponentUpdate`, therefore it will **not** rerender unless its props has changed.

Each `<Child>` then contains the `<Link />` component with `activeClassName` supplied, which has no way to rerender itself when I navigate to a new route. Eg. /items/1 => /items/2. 

List: 
```
...
// on clicking a child, this should change the data supplied to the child, triggering a rerender on whichever child I clicked. 
render() {
    return (
         <div>
                <Child id='1' { ...child_1_data } />
                <Child id='2' { ...child_2_data } />
         <div>
    )
}
...
```

Child:
```
...
shouldComponentUpdate(nextProps) {
    // for brevity sake lets say this works like deep compare
    return this.props !== nextProps;
}

render() {
    return <Link to={ `/items/${ this.props.id }` } activeClassName='active' />
}
...
```

## Expected Behavior

From Child 1 (currently active), I click Child 2, route change from /items/1 => /items/2, then Child 1 should remove its active class. 

## Actual Behavior

Child 1 does not remove its active class.

## Suggestion

This is happening because `<Link />` only rerenders itself when its containing parent accepts an update. In the scenario I've given, my `Child`s do not update themselves unless data has changed. 

I suggest that `<Link />` listens to the route changes directly on `componentDidMount` and unlisten on `componentWillUnmount`. This allows them to update themselves in cases where their parent component do not update, which is highly possible for applications that optimize using `shouldComponentUpdate`.

**Comment by geekyme** [comment] 2016-03-18 12:04
A possible solution here is to compose Link in a higher order component, and bind to route changes at the higher level then call forceUpdate() on change.

**Comment by timdorr** [comment] 2016-03-18 14:33
Dupe of #470

**Closed by timdorr** 2016-03-18 14:33 UTC
Labels: duplicate
