### ISSUE TITLE
query string parse malformed issue

### ISSUE THREAD

**Issue by donemin** [reactjs/react-router#3658] opened 2016-07-21 06:31 UTC
I route url like "http://asdf.asdf.com/search?keyword=blahblah"

if "blahblah" is valid query string, it's not problem.

but query string value "%" then emit malformed error (eg. http://asdf.asdf.com/search?keyword=%)

I tracked source and found 'query-string' dependency emit error.

How can I fix it? is it intended?

I thing use query-string parse centainly try catch.

error emit in code  decodeURIComponent function.

help plz.

**Comment by taion** [comment] 2016-07-21 06:43
Please search existing issues before opening new ones. This is a dupe of https://github.com/reactjs/react-router/issues/3507.

**Closed by taion** 2016-07-21 06:43 UTC
