### ISSUE TITLE
:paramName doesn't match URL segments containing dot '.' and hyphen '-'

### ISSUE THREAD

**Issue by capouch** [reactjs/react-router#3409] opened 2016-04-28 22:47 UTC
The documentation for Router parameters indicates that 

`:paramName – matches a URL segment up to the next /, ?, or #. The matched string is called a param`

But when I pass in this URL:

`/zoomer/stmarks.tif-1461881719816`

against this route:

`<Route path="zoomer/:imageId" component={ Zoom }/>`

The route doesn't match and 404s.  Removing the period and hyphen fixes the problem.  

Am I misunderstanding the documentation?  Those characters shouldn't have to be escaped. . .

**Comment by taion** [comment] 2016-04-28 22:57
This works fine for me. Possibly a dupe of https://github.com/reactjs/react-router/issues/3402? If you can put together a repro plus information on browser details, we'd be happy to take a look.

**Closed by taion** 2016-04-28 22:57 UTC

**Comment by capouch** [comment] 2016-04-28 23:22
I duped the repo to a cloud server to send you and VERY STRANGE:  Same browser environment (Chrome Beta) and same server environment (Node running webpack bundle) but the localhost instance gives me an error but the cloud one works just fine.  Sorry for the noise, thanks for the help.

**Comment by SergeyKorchevskiy** [comment] 2016-05-23 04:10
I tried `react-router` with `history`, and I am getting same issue. 
When I enter `http://localhost:8080/token/some.token`, it gives me error, but when I enter `http://localhost:8080/token/sometoken`, it works fine. 
@taion , or any one from React Community Member can help me with this?

Here's my repo. https://github.com/SergeyKorchevskiy/react-router-issue-example
Let me describe the steps for running app for convenience. 
```sh
$ git clone git@github.com:SergeyKorchevskiy/react-router-issue-example.git
$ cd react-router-issue-example
$ npm i
$ npm start
```

**Comment by taion** [comment] 2016-05-23 12:44
This is most likely an issue with your server config.

**Comment by kalmanb** [comment] 2016-06-27 03:42
I had the same issue proved to be webpack dev server with history-api-fallback enabled failed to pass these urls to the react app. Hacked webpack config to pass these to react with:
```
...
devServer: {
  proxy: {
    '/*.*': { // Match all URL's with period/dot
      target: 'http://localhost:8080/',  // send to webpack dev server
      rewrite: function(req){
        req.url='index.html';  // Send to react app
      }
    }
  }
}
...
```

**Comment by mcrawshaw** [comment] 2017-01-11 23:03
I only had an issue with period (not hyphen).  I resolved by adding this to my webpack dev server config:
```
  historyApiFallback: {
    disableDotRule: true
  }
```

See https://github.com/bripkens/connect-history-api-fallback/issues/25

**Comment by petervojtek** [comment] 2017-08-28 17:54
when I add `disableDotRule: true` to webpack config, my app starts to fail with `whitelist.js:1 Uncaught SyntaxError: Unexpected token <`. 
I use node 8.4.0.

**Comment by EmilianoBarbozaOjeda** [comment] 2017-11-28 17:33
Hi all, I'm having same issue as @petervojtek 
I'm using the default dev-server.js from webpack

`// handle fallback for HTML5 history API
app.use(require('connect-history-api-fallback')({disableDotRule: true}))`

I'm trying to support this kind of urls:
`http://mydomain.com/somePage/%242y%2410%24Xd6XF0vPA7fhHhzOoOfb9OIFm1SZ.lep.ccQaIMI.PELasQsZj6rC`

The parameter is a urlencoded

Has something changed in the way to enable dots in url?
