### ISSUE TITLE
Routes with a `getComponent` hook will never trigger `onChange` hook

### ISSUE THREAD

**Issue by Swatinem** [reactjs/react-router#3516] opened 2016-06-06 12:37 UTC
## Version
2.0.0

## Test Case
http://codepen.io/anon/pen/zBvYXQ?editors=0011

## Steps to reproduce

Click the 1 / 2 links of the *with getComponent* line repeatedly

## Expected Behavior

should call `onChange` hook for the route

## Actual Behavior

instead calls the `onEnter` (and `onLeave`) hook for the route

**Comment by taion** [comment] 2016-06-06 14:20
Dupe of https://github.com/reactjs/react-router/issues/3476 – your `getComponent` is actually never invoking the cb, which is why you see that behavior.

**Closed by taion** 2016-06-06 14:20 UTC
